### ISSUE TITLE
How do you write unit tests for  your react/preact apps?

### ISSUE THREAD

**Issue by madhurgarg71** [siddharthkp/ama#1]
I know there are tools like Jest, but how do you actually figure it out what need to be tested? Is it more of snapshot testing or what?

**Comment by siddharthkp** [comment]
I love this question, thanks for asking!

Jest at it's core is a test runner, it will let you pick your strategy and run it for you. I use Jest for all my React applications ([ava](https://github.com/avajs/ava) for node backends)

Warning: I have a lot of opinions on this, so it's a long answer 😄 

----

It's usually a good idea to split your components into 2 categories:

**I) Presentational/Stateless**: These components don't have state. They govern the look and feel.

You want to test these with snapshots.

Take this button as an example:

```js
import React from 'react'

const Button = () => <button
  style={{
    background: '#fff',
    color: '#000'
  }}
>
  Click me!
</button>

export default Button
```

I'm using inline styles to keep this simple, but the same would apply with a css-in-js library as well.

And let's say a Form component uses this button as well.

```js
import React from 'react'
import Button from './button'

const Form = () => <form>
  <input type="text"/>
  <Button/>
</form>

export default Button
```

Writing tests that confirm that a button is created with the correct background and color is not very useful. But you do want to track the changes that happen to this component in the future and make sure there are no mistakes/bugs.

This is the perfect use case for snapshot testing. The idea here is that you take a "snapshot" of the current render output of this component and store it in your repository.

The code to make this happen looks something like this:

```js
import React from 'react'
import Button from './button'
import renderer from 'react-test-renderer'

test(`Here's a button!`, () => {
  const button = renderer.create(<Button />) // render the component
  let tree = button.toJSON() // create an object representation of it
  expect(tree).toMatchSnapshot() // compare it with the previous snapshot if it exists
})
```

The test for the form component would look very similar.

This is what the snapshot looks like:

```js
exports[`Here's a button! 1`] = `
<button
  style={
    Object {
      "background": "#fff",
      "color": "#000",
    }
  }
>
  Click me!
</button>
`;
```

As you can see the snapshot is just a representation of your component. This is the source of truth now.

Now, in the future, if we want to change the background of the button. Jest will warn us about the changes:

```diff
Received value does not match stored snapshot.


<button
  style={
    Object {
-      "background": "#fff",
+      "background": "#08b",
         "color": "#000",
       }
     }
>
  Click me!
</button>

at Object.<anonymous>.test (src/components/button.test.js:8:16)
```

Not only for your Button component, you will also get a failed test for your Form component that used the button! This way you get to know what all changes when you change a tiny component.

Now you have 2 options:
1. "Accept and update" your snapshots because the changes are intentional.
2. Realise that there's an unintentional change here and fix your code.

I really like snapshot testing because it helps me prevent potential bugs with very little work.
And, as we commit these snapshots to the repository, I can also look at them while reviewing a PR on github :rocket: (sometimes, I skip the code and just look at the snapshot diff :wink:)

---

Now let's talk about the other type of component.

**II. Stateful components:**

These components handle user interactions, data fetching, etc.

Let's add some state to our component.
The button is only enabled when there is content in the input box.

```js
import React from 'react'
import Button from './button'

class Form extends React.Component {
  constructor() {
    // default state of the button is disabled as there is no content
    this.state = { disabled: true }
  }
  onChange(event) {
    // if there's value in the input box, set disabled to false
    if (event.target.value) this.setState({ disabled: false })
    else this.setState({ disabled: true })
  }
  render() {
    // 1. add the above method to the onChange of the input
    // 2. use the disabled from component's state to add disabled prop
    return (
      <form>
        <input onChange={this.onChange.bind(this)} />
        <Button disabled={this.state.disabled} />
      </form>
    )
  }
}

export default Form
```

As our Form component has multiple states, we cannot rely on a snapshot that only captures it's initial state.

We want to trigger changes to the state by simulating what a user would do.

There are 2 ways to approach this:

a) Approach 1: Multiple snapshots

Let's first create a test case to capture the initial state of the component

```js
test('Initial state', () => {
  const component = renderer.create(<Form />)
  let tree = component.toJSON()
  expect(tree).toMatchSnapshot()
})
```

Now, we want to create another test case where we simulate user action and trigger a state change.

```js
test('State after text in the input box', () => {
  const component = renderer.create(<Form/>)
  let tree = component.toJSON()

  /*
    Business as usual till here.
    But, this time, instead of matching this tree with the snapshot,
    we will get the input from the tree and trigger the onChange function
  */

  const input = tree.children[0] // we know it's the first element in render
  input.props.onChange({ target: { value: 'a' } }) // this will trigger the onChange function!

  // Let's create a snapshot of our altered tree and save that!
  tree = component.toJSON()
  expect(tree).toMatchSnapshot()
})
```

Jest will create 2 snapshots for us.

There's a tiny problem with this approach, because this is not as straightforward/predictable as our presentation component test,
you should confirm the snapshot that has been created to make sure it will do it's job.

Not everyone likes this approach. It might not give you enough confidence in the test, especially if you're working in a team.

b) Approach 2: Confirm (expect) the properties

Instead of creating snapshots, we can also read the properties from the rendered component and write tests on top of it.

```js
// replace react-test-renderer with enzyme
import { mount } from 'enzyme'
// add chai to use expect
import { expect } from 'chai'
// you need to import jsdom-global/register
// to create a DOM that enzyme can render/mount components onto
import 'jsdom-global/register'

// mount = render the component
const wrapper = mount(<Form />)
// get the dom elements we need to check
const input = wrapper.find('input')
const button = wrapper.find('button')

// let's write some tests now

it('button is disabled by default', () => {
  expect(button.props().disabled).to.equal(true)
})

it('button is enabled when text changes', () => {
  // simulate what the user would do
  input.getDOMNode().value = 'a'
  input.simulate('change')
  expect(button.props().disabled).to.equal(false)
})
```

As you should notice, these tests are more explicit in nature than the ones we wrote before.

Note: enzyme has a `shallow` rendering method as well, it renders the component without it's children. I recommend always using `mount` which renders the entire children tree.

---

My favourite strategy is to

- write a bunch of snapshot tests for my atomic presentation components like button, anchor, input box, etc.
- skip presentation components in the application that just take data as props and render jsx
- write explicit tests for stateful components with enzyme + chai for user interactions that change state

---

Side notes:

- If your components fetch data, you might want to [mock the API requests](https://hackernoon.com/api-testing-with-jest-d1ab74005c0a) (for speed and consistency both)
- Write tests to make your code bug-proof for the future. Tests that don't contribute to this cause are just more code to maintain. Don't run after coverage numbers (I've done this mistake a lot of times). [More on that here](https://tinyletter.com/kentcdodds/letters/write-tests-not-too-many-mostly-integration)
- The question Jest or Enzyme is kinda invalid. See our last example, we wrote our tests with enzyme and jest is going to run them, they work great together!

---

Thanks for asking me this question and helping me articulate my thoughts on this!

&nbps;

**Comment by siddharthkp** [comment]
Hope this helped!

**Comment by madhurgarg71** [comment]
Thanks a lot!

**Comment by madhurgarg71** [comment]
@siddharthkp It would be great if you can include this topic in your next talk, just as a little part of your presentation. :)
